#define	CAN_ERR_HV_SHUTDOWN						0x000

#define	CAN_MSG_MOTOR_LEFT_RX					0x181
#define	CAN_MSG_MOTOR_RIGHT_RX					0x182
#define	CAN_MSG_MOTOR_LEFT_TX					0x201
#define	CAN_MSG_MOTOR_RIGHT_TX					0x202

#define	CAN_ERR_PEDALS_IMPLAUSIBILITY			0x300
#define	CAN_MSG_PEDALS							0x310
#define	CAN_MSG_STEERING						0x311
#define	CAN_MSG_PEDALS_CALIBRATE				0x320
#define	CAN_MSG_PEDALS_CALIBRATION_COMPLETE		0x321

#define	CAN_MSG_USER_START						0x400
#define	CAN_MSG_USER_STOP						0x401
#define	CAN_MSG_WHEEL_RPM_FRONT					0x450
